export interface Tutor {
  id: string
  name: string
  avatar: string
  bio: string
  rating: number
  totalReviews: number
  hourlyRate: number
  specialties: string[]
  studentsCount: number
  responseTime: string
}

export interface Skill {
  id: string
  title: string
  description: string
  tutorId: string
  tutorName: string
  tutorAvatar: string
  category: string
  level: "Beginner" | "Intermediate" | "Advanced"
  price: number
  rating: number
  reviews: number
  image: string
  createdAt: Date
  courseOverview: string[]
  skillsLearned: string[]
  duration: string
  students: number
}

export interface Review {
  id: string
  tutorId: string
  tutorName: string
  tutorAvatar: string
  rating: number
  comment: string
  studentName: string
  studentAvatar: string
  courseTitle?: string
  createdAt: Date
  status?: string
}

export interface BookingSession {
  id: string
  tutorId: string
  skillId: string
  studentName: string
  date: Date
  time: string
  status: "pending" | "confirmed" | "completed"
}

// Mock Tutors Data
export const mockTutors: Tutor[] = [
  {
    id: "tutor-1",
    name: "Sarah Johnson",
    avatar: "/professional-woman-tutor.jpg",
    bio: "Expert web developer with 8 years of experience. Passionate about teaching React and modern JavaScript.",
    rating: 4.9,
    totalReviews: 156,
    hourlyRate: 50,
    specialties: ["React", "JavaScript", "Web Development", "CSS"],
    studentsCount: 342,
    responseTime: "< 1 hour",
  },
  {
    id: "tutor-2",
    name: "Michael Chen",
    avatar: "/professional-man-designer.jpg",
    bio: "UI/UX Designer and Illustrator. Specializing in digital art and design thinking.",
    rating: 4.8,
    totalReviews: 124,
    hourlyRate: 45,
    specialties: ["UI Design", "Illustration", "Figma", "Design Thinking"],
    studentsCount: 287,
    responseTime: "< 2 hours",
  },
  {
    id: "tutor-3",
    name: "Emma Wilson",
    avatar: "/professional-woman-photographer.jpg",
    bio: "Professional photographer and videographer. Teaching photography fundamentals and editing.",
    rating: 4.7,
    totalReviews: 98,
    hourlyRate: 55,
    specialties: ["Photography", "Videography", "Lightroom", "Composition"],
    studentsCount: 215,
    responseTime: "< 3 hours",
  },
  {
    id: "tutor-4",
    name: "David Kumar",
    avatar: "/professional-man-musician.jpg",
    bio: "Music producer and guitarist. Offering lessons in music production and guitar playing.",
    rating: 4.6,
    totalReviews: 87,
    hourlyRate: 40,
    specialties: ["Music Production", "Guitar", "Logic Pro", "Songwriting"],
    studentsCount: 198,
    responseTime: "< 4 hours",
  },
  {
    id: "tutor-5",
    name: "Lisa Anderson",
    avatar: "/professional-woman-chef.jpg",
    bio: "Professional chef and cooking instructor. Specializing in international cuisines.",
    rating: 4.9,
    totalReviews: 142,
    hourlyRate: 35,
    specialties: ["Cooking", "Baking", "Italian Cuisine", "Nutrition"],
    studentsCount: 267,
    responseTime: "< 1 hour",
  },
  {
    id: "tutor-6",
    name: "James Martinez",
    avatar: "/professional-man-fitness.jpg",
    bio: "Certified fitness trainer and nutritionist. Helping students achieve their fitness goals.",
    rating: 4.8,
    totalReviews: 165,
    hourlyRate: 30,
    specialties: ["Fitness", "Nutrition", "Yoga", "Personal Training"],
    studentsCount: 412,
    responseTime: "< 2 hours",
  },
]

export const mockSkills: Skill[] = [
  {
    id: "skill-1",
    title: "React Fundamentals",
    description: "Learn the basics of React including components, hooks, and state management.",
    tutorId: "tutor-1",
    tutorName: "Sarah Johnson",
    tutorAvatar: "/professional-woman-tutor.jpg",
    category: "Web Development",
    level: "Beginner",
    price: 50,
    rating: 4.9,
    reviews: 156,
    image: "/react-course.jpg",
    createdAt: new Date("2024-10-25"),
    courseOverview: [
      "Introduction to React and JSX",
      "Components and Props",
      "State and Hooks",
      "Event Handling",
      "Conditional Rendering",
      "Lists and Keys",
      "Forms and Controlled Components",
      "Lifting State Up",
    ],
    skillsLearned: [
      "Build dynamic user interfaces",
      "Understand React component lifecycle",
      "Master React Hooks",
      "Manage application state",
      "Handle user interactions",
      "Create reusable components",
    ],
    duration: "4 weeks",
    students: 342,
  },
  {
    id: "skill-2",
    title: "Advanced JavaScript",
    description: "Master advanced JavaScript concepts like closures, async/await, and design patterns.",
    tutorId: "tutor-1",
    tutorName: "Sarah Johnson",
    tutorAvatar: "/professional-woman-tutor.jpg",
    category: "Web Development",
    level: "Advanced",
    price: 60,
    rating: 4.8,
    reviews: 98,
    image: "/javascript-course.jpg",
    createdAt: new Date("2024-10-24"),
    courseOverview: [
      "Closures and Scope",
      "Prototypes and Inheritance",
      "Async/Await and Promises",
      "Error Handling",
      "Design Patterns",
      "Performance Optimization",
      "Memory Management",
      "Advanced Array Methods",
    ],
    skillsLearned: [
      "Master closures and scope chains",
      "Understand prototypal inheritance",
      "Work with Promises and async/await",
      "Implement design patterns",
      "Optimize JavaScript performance",
      "Debug and troubleshoot code",
    ],
    duration: "6 weeks",
    students: 287,
  },
  {
    id: "skill-3",
    title: "UI/UX Design Principles",
    description: "Learn the fundamentals of user interface and user experience design.",
    tutorId: "tutor-2",
    tutorName: "Michael Chen",
    tutorAvatar: "/professional-man-designer.jpg",
    category: "Design",
    level: "Beginner",
    price: 45,
    rating: 4.8,
    reviews: 124,
    image: "/ui-design-course.jpg",
    createdAt: new Date("2024-10-23"),
    courseOverview: [
      "Design Fundamentals",
      "Color Theory and Psychology",
      "Typography and Fonts",
      "User Research",
      "Wireframing and Prototyping",
      "Usability Testing",
      "Design Systems",
      "Accessibility Guidelines",
    ],
    skillsLearned: [
      "Create intuitive user interfaces",
      "Understand user needs and pain points",
      "Design accessible experiences",
      "Build design systems",
      "Conduct user research",
      "Create effective prototypes",
    ],
    duration: "5 weeks",
    students: 215,
  },
  {
    id: "skill-4",
    title: "Digital Illustration",
    description: "Create stunning digital illustrations using Procreate and Adobe Creative Suite.",
    tutorId: "tutor-2",
    tutorName: "Michael Chen",
    tutorAvatar: "/professional-man-designer.jpg",
    category: "Art & Design",
    level: "Intermediate",
    price: 50,
    rating: 4.7,
    reviews: 87,
    image: "/illustration-course.jpg",
    createdAt: new Date("2024-10-22"),
    courseOverview: [
      "Digital Art Basics",
      "Brush Techniques",
      "Color Mixing and Blending",
      "Character Design",
      "Environment Design",
      "Perspective and Anatomy",
      "Animation Fundamentals",
      "Exporting and Publishing",
    ],
    skillsLearned: [
      "Master digital painting techniques",
      "Create original characters",
      "Build immersive environments",
      "Understand perspective and anatomy",
      "Use professional software",
      "Prepare artwork for publication",
    ],
    duration: "6 weeks",
    students: 198,
  },
  {
    id: "skill-5",
    title: "Photography Masterclass",
    description: "Master photography composition, lighting, and post-processing techniques.",
    tutorId: "tutor-3",
    tutorName: "Emma Wilson",
    tutorAvatar: "/professional-woman-photographer.jpg",
    category: "Photography",
    level: "Intermediate",
    price: 55,
    rating: 4.9,
    reviews: 142,
    image: "/photography-course.jpg",
    createdAt: new Date("2024-10-21"),
    courseOverview: [
      "Camera Basics and Settings",
      "Composition Techniques",
      "Lighting Fundamentals",
      "Portrait Photography",
      "Landscape Photography",
      "Post-Processing with Lightroom",
      "Adobe Photoshop for Photos",
      "Building Your Portfolio",
    ],
    skillsLearned: [
      "Master camera settings and modes",
      "Create compelling compositions",
      "Control lighting and exposure",
      "Retouch and enhance photos",
      "Specialize in portrait or landscape",
      "Build a professional portfolio",
    ],
    duration: "7 weeks",
    students: 267,
  },
  {
    id: "skill-6",
    title: "Music Production Basics",
    description: "Learn music production from scratch using Logic Pro and industry-standard tools.",
    tutorId: "tutor-4",
    tutorName: "David Kumar",
    tutorAvatar: "/professional-man-musician.jpg",
    category: "Music",
    level: "Beginner",
    price: 40,
    rating: 4.6,
    reviews: 76,
    image: "/music-production-course.jpg",
    createdAt: new Date("2024-10-20"),
    courseOverview: [
      "DAW Setup and Configuration",
      "Recording Basics",
      "MIDI Programming",
      "Mixing Fundamentals",
      "EQ and Compression",
      "Effects and Reverb",
      "Mastering Basics",
      "Publishing Your Tracks",
    ],
    skillsLearned: [
      "Use professional DAW software",
      "Record and arrange music",
      "Program MIDI instruments",
      "Mix audio professionally",
      "Apply effects and processing",
      "Master and prepare for release",
    ],
    duration: "6 weeks",
    students: 412,
  },
  {
    id: "skill-7",
    title: "Guitar for Beginners",
    description: "Start your guitar journey with fundamental techniques and popular songs.",
    tutorId: "tutor-4",
    tutorName: "David Kumar",
    tutorAvatar: "/professional-man-musician.jpg",
    category: "Music",
    level: "Beginner",
    price: 35,
    rating: 4.7,
    reviews: 98,
    image: "/guitar-course.jpg",
    createdAt: new Date("2024-10-19"),
    courseOverview: [
      "Guitar Parts and Names",
      "Tuning and Maintenance",
      "Basic Chords",
      "Strumming Patterns",
      "Fingerpicking Techniques",
      "Music Theory Basics",
      "Playing Popular Songs",
      "Reading Guitar Tabs",
    ],
    skillsLearned: [
      "Play basic and complex chords",
      "Master strumming and fingerpicking",
      "Read guitar tabs and music notation",
      "Play popular songs",
      "Understand music theory",
      "Maintain your guitar",
    ],
    duration: "8 weeks",
    students: 156,
  },
  {
    id: "skill-8",
    title: "Italian Cooking",
    description: "Learn authentic Italian cooking techniques and traditional recipes.",
    tutorId: "tutor-5",
    tutorName: "Lisa Anderson",
    tutorAvatar: "/professional-woman-chef.jpg",
    category: "Cooking",
    level: "Beginner",
    price: 35,
    rating: 4.9,
    reviews: 156,
    image: "/cooking-course.jpg",
    createdAt: new Date("2024-10-18"),
    courseOverview: [
      "Italian Ingredients Essentials",
      "Making Fresh Pasta",
      "Authentic Sauces",
      "Risotto Techniques",
      "Pizza Making",
      "Seafood Dishes",
      "Traditional Desserts",
      "Wine Pairing Basics",
    ],
    skillsLearned: [
      "Master Italian cooking techniques",
      "Make pasta from scratch",
      "Prepare authentic sauces",
      "Cook regional specialties",
      "Create traditional desserts",
      "Pair food with wine",
    ],
    duration: "5 weeks",
    students: 334,
  },
  {
    id: "skill-9",
    title: "Fitness Training",
    description: "Personalized fitness training program tailored to your goals.",
    tutorId: "tutor-6",
    tutorName: "James Martinez",
    tutorAvatar: "/professional-man-fitness.jpg",
    category: "Fitness",
    level: "Beginner",
    price: 30,
    rating: 4.8,
    reviews: 165,
    image: "/fitness-course.jpg",
    createdAt: new Date("2024-10-17"),
    courseOverview: [
      "Fitness Fundamentals",
      "Strength Training",
      "Cardio Training",
      "Flexibility and Mobility",
      "Nutrition Basics",
      "Recovery and Rest",
      "Injury Prevention",
      "Progressive Overload",
    ],
    skillsLearned: [
      "Build strength and muscle",
      "Improve cardiovascular health",
      "Increase flexibility and mobility",
      "Understand proper nutrition",
      "Prevent common injuries",
      "Create personalized workout plans",
    ],
    duration: "12 weeks",
    students: 523,
  },
  {
    id: "skill-10",
    title: "Yoga & Meditation",
    description: "Learn yoga poses, breathing techniques, and meditation for wellness.",
    tutorId: "tutor-6",
    tutorName: "James Martinez",
    tutorAvatar: "/professional-man-fitness.jpg",
    category: "Fitness",
    level: "Beginner",
    price: 25,
    rating: 4.7,
    reviews: 134,
    image: "/yoga-course.jpg",
    createdAt: new Date("2024-10-16"),
    courseOverview: [
      "Yoga History and Philosophy",
      "Basic Yoga Poses (Asanas)",
      "Breathing Techniques (Pranayama)",
      "Meditation Fundamentals",
      "Sun Salutation Flow",
      "Restorative Yoga",
      "Chakra Balancing",
      "Creating a Home Practice",
    ],
    skillsLearned: [
      "Master fundamental yoga poses",
      "Practice breathing techniques",
      "Meditate effectively",
      "Reduce stress and anxiety",
      "Improve flexibility and balance",
      "Create a sustainable practice",
    ],
    duration: "4 weeks",
    students: 287,
  },
]

// Mock Reviews Data
export const mockReviews: Review[] = [
  {
    id: "review-1",
    tutorId: "tutor-1",
    tutorName: "Sarah Johnson",
    tutorAvatar: "/professional-woman-tutor.jpg",
    rating: 5,
    comment: "Excellent instructor! Very clear explanations and patient with questions.",
    studentName: "Alex Thompson",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-25"),
  },
  {
    id: "review-2",
    tutorId: "tutor-1",
    tutorName: "Sarah Johnson",
    tutorAvatar: "/professional-woman-tutor.jpg",
    rating: 5,
    comment: "Best React course I've taken. Highly recommended!",
    studentName: "Jordan Lee",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-24"),
  },
  {
    id: "review-3",
    tutorId: "tutor-2",
    tutorName: "Michael Chen",
    tutorAvatar: "/professional-man-designer.jpg",
    rating: 5,
    comment: "Amazing design instructor. Very creative and inspiring!",
    studentName: "Casey Morgan",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-23"),
  },
  {
    id: "review-4",
    tutorId: "tutor-3",
    tutorName: "Emma Wilson",
    tutorAvatar: "/professional-woman-photographer.jpg",
    rating: 4,
    comment: "Great photography tips. Could use more practice sessions.",
    studentName: "Taylor Brown",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-22"),
  },
  {
    id: "review-5",
    tutorId: "tutor-4",
    tutorName: "David Kumar",
    tutorAvatar: "/professional-man-musician.jpg",
    rating: 4,
    comment: "Good music production course. Very informative.",
    studentName: "Riley Davis",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-21"),
  },
  {
    id: "review-6",
    tutorId: "tutor-5",
    tutorName: "Lisa Anderson",
    tutorAvatar: "/professional-woman-chef.jpg",
    rating: 5,
    comment: "Delicious recipes and excellent teaching style!",
    studentName: "Morgan White",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-20"),
  },
  {
    id: "review-7",
    tutorId: "tutor-6",
    tutorName: "James Martinez",
    tutorAvatar: "/professional-man-fitness.jpg",
    rating: 5,
    comment: "Transformed my fitness routine. Highly professional!",
    studentName: "Jordan Green",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-19"),
  },
  {
    id: "review-8",
    tutorId: "tutor-1",
    tutorName: "Sarah Johnson",
    tutorAvatar: "/professional-woman-tutor.jpg",
    rating: 4,
    comment: "Very good course, but could use more real-world projects.",
    studentName: "Casey Blue",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-18"),
  },
  {
    id: "review-9",
    tutorId: "tutor-2",
    tutorName: "Michael Chen",
    tutorAvatar: "/professional-man-designer.jpg",
    rating: 4,
    comment: "Good design principles. Needs more hands-on projects.",
    studentName: "Alex Purple",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-17"),
  },
  {
    id: "review-10",
    tutorId: "tutor-3",
    tutorName: "Emma Wilson",
    tutorAvatar: "/professional-woman-photographer.jpg",
    rating: 3,
    comment: "Decent photography course, but could be more detailed.",
    studentName: "Jordan Red",
    studentAvatar: "/student-avatar.jpg",
    createdAt: new Date("2024-10-16"),
  },
]
